language: php
sudo: false
install: composer install

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
